CREATE TABLE IF NOT EXISTS adp__users (
  user_id VARCHAR(255) PRIMARY KEY,
  username VARCHAR(255),
  avatar VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);
